/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import Controlador.Controller;
import Parseador.Parser;
import java.awt.Color;
import javax.swing.JTextField;

/**
 *
 * @author rauldiego
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    private Controller control;//Se comunica con el controlador para llevar a cabo las funcionalidades requeridas
    private Parser mapCartas;//Llama al parser para elaborar el map con todas las cartas
    private char fase = 'P';//Se indica que fase del juego estan
    private int numJugador;
    /*private JTextField arrayDeCampos [] = new JTextField[13];
    private boolean empezada;
    private boolean cartascogias[] = new boolean[169];
    private int turno;*/
    
    private static String todosLosPares[] = {"AA", "AKs", "AQs", "AJs", "ATs", "A9s", "A8s", "A7s",
        "A6s", "A5s", "A4s", "A3s", "A2s",
        "AKo", "KK", "KQs", "KJs", "KTs", "K9s", "K8s", "K7s", "K6s", "K5s", "K4s", "K3s", "K2s",
        "AQo", "KQo", "QQ", "QJs", "QTs", "Q9s", "Q8s", "Q7s", "Q6s", "Q5s", "Q4s", "Q3s", "Q2s",
        "AJo", "KJo", "QJo", "JJ", "JTs", "J9s", "J8s", "J7s", "J6s", "J5s", "J4s", "J3s", "J2s",
        "ATo", "KTo", "QTo", "JTo", "TT", "T9s", "T8s", "T7s", "T6s", "T5s", "T4s", "T3s", "T2s",
        "A9o", "K9o", "Q9o", "J9o", "T9o", "99", "98s", "97s", "96s", "95s", "94s", "93s", "92s",
        "A8o", "K8o", "Q8o", "J8o", "T8o", "98o", "88", "87s", "86s", "85s", "84s", "83s", "82s",
        "A7o", "K7o", "Q7o", "J7o", "T7o", "97o", "87o", "77", "76s", "75s", "74s", "73s", "72s",
        "A6o", "K6o", "Q6o", "J6o", "T6o", "96o", "86o", "76o", "66", "65s", "64s", "63s", "62s",
        "A5o", "K5o", "Q5o", "J5o", "T5o", "95o", "85o", "75o", "65o", "55", "54s", "53s", "52s",
        "A4o", "K4o", "Q4o", "J4o", "T4o", "94o", "84o", "74o", "64o", "54o", "44", "43s", "42s",
        "A3o", "K3o", "Q3o", "J3o", "T3o", "93o", "83o", "73o", "63o", "53o", "43o", "33", "32s",
        "A2o", "K2o", "Q2o", "J2o", "T2o", "92o", "82o", "72o", "62o", "52o", "42o", "32o", "22",};
    
    public GUI() {
        initComponents();
        mapCartas = new Parser();
        control = new Controller(mapCartas.getCartas(), fase);
        /*empezada = false;
        turno = 0;*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_Player1 = new javax.swing.JTextField();
        jTextField_Player2 = new javax.swing.JTextField();
        jTextField_Player3 = new javax.swing.JTextField();
        jTextField_Player4 = new javax.swing.JTextField();
        jTextField_Player5 = new javax.swing.JTextField();
        jTextField_Player6 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jButton_Aplicar = new javax.swing.JButton();
        jButtonRiver = new javax.swing.JButton();
        jButtonTurn = new javax.swing.JButton();
        jButtonFlop3 = new javax.swing.JButton();
        jButtonFLop2 = new javax.swing.JButton();
        jButtonFlop1 = new javax.swing.JButton();
        jButtonPlayer2_2 = new javax.swing.JButton();
        jButtonPlayer2_1 = new javax.swing.JButton();
        jButtonPlayer6_2 = new javax.swing.JButton();
        jButtonPlayer6_1 = new javax.swing.JButton();
        jButtonPlayer5_2 = new javax.swing.JButton();
        jButtonPlayer5_1 = new javax.swing.JButton();
        jButtonPlayer4_2 = new javax.swing.JButton();
        jButtonPlayer4_1 = new javax.swing.JButton();
        jButtonPlayer3_1 = new javax.swing.JButton();
        jButtonPlayer3_2 = new javax.swing.JButton();
        jButtonPlayer1_1 = new javax.swing.JButton();
        jButtonPlayer1_2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 200, -1));
        getContentPane().add(jTextField_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 690, 200, -1));
        getContentPane().add(jTextField_Player3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 690, 200, -1));
        getContentPane().add(jTextField_Player4, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 480, 200, -1));
        getContentPane().add(jTextField_Player5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 200, -1));

        jTextField_Player6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Player6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField_Player6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 200, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 30));
        jTextField1.setVisible(false);

        jButton_Aplicar.setText("Aplicar");
        getContentPane().add(jButton_Aplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 90, 30));
        jButton_Aplicar.setBorder(null);
        jButton_Aplicar.setVisible(false);

        jButtonRiver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonRiver, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 120, 160));
        jButtonRiver.setBorder(null);

        jButtonTurn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, 120, 160));
        jButtonTurn.setBorder(null);

        jButtonFlop3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonFlop3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 120, 160));
        jButtonFlop3.setBorder(null);

        jButtonFLop2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonFLop2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 120, 160));
        jButtonFLop2.setBorder(null);

        jButtonFlop1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonFlop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 120, 160));
        jButtonFlop1.setBorder(null);

        jButtonPlayer2_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 100, 130));
        jButtonPlayer2_2.setBorder(null);

        jButtonPlayer2_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 100, 130));
        jButtonPlayer2_1.setBorder(null);

        jButtonPlayer6_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer6_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 100, 130));
        jButtonPlayer6_2.setBorder(null);

        jButtonPlayer6_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 100, 130));
        jButtonPlayer6_1.setBorder(null);

        jButtonPlayer5_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 100, 130));
        jButtonPlayer5_2.setBorder(null);

        jButtonPlayer5_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 100, 130));
        jButtonPlayer5_1.setBorder(null);

        jButtonPlayer4_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, 100, 130));
        jButtonPlayer4_2.setBorder(null);

        jButtonPlayer4_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 350, 100, 130));
        jButtonPlayer4_1.setBorder(null);

        jButtonPlayer3_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 100, 130));
        jButtonPlayer3_1.setBorder(null);

        jButtonPlayer3_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayer3_2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPlayer3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 560, 100, 130));
        jButtonPlayer3_2.setBorder(null);

        jButtonPlayer1_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        getContentPane().add(jButtonPlayer1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 130));
        jButtonPlayer1_1.setBorder(null);

        setVisible(false);
        jButtonPlayer1_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carta.PNG"))); // NOI18N
        jButtonPlayer1_2.setText("jButton2");
        getContentPane().add(jButtonPlayer1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 100, 130));
        jButtonPlayer1_2.setBorder(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mesa.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 750, 350));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-negro.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1150, 920));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlayer3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayer3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPlayer3_2ActionPerformed

    private void jTextField_Player6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Player6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Player6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFLop2;
    private javax.swing.JButton jButtonFlop1;
    private javax.swing.JButton jButtonFlop3;
    private javax.swing.JButton jButtonPlayer1_1;
    private javax.swing.JButton jButtonPlayer1_2;
    private javax.swing.JButton jButtonPlayer2_1;
    private javax.swing.JButton jButtonPlayer2_2;
    private javax.swing.JButton jButtonPlayer3_1;
    private javax.swing.JButton jButtonPlayer3_2;
    private javax.swing.JButton jButtonPlayer4_1;
    private javax.swing.JButton jButtonPlayer4_2;
    private javax.swing.JButton jButtonPlayer5_1;
    private javax.swing.JButton jButtonPlayer5_2;
    private javax.swing.JButton jButtonPlayer6_1;
    private javax.swing.JButton jButtonPlayer6_2;
    private javax.swing.JButton jButtonRiver;
    private javax.swing.JButton jButtonTurn;
    private javax.swing.JButton jButton_Aplicar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_Player1;
    private javax.swing.JTextField jTextField_Player2;
    private javax.swing.JTextField jTextField_Player3;
    private javax.swing.JTextField jTextField_Player4;
    private javax.swing.JTextField jTextField_Player5;
    private javax.swing.JTextField jTextField_Player6;
    // End of variables declaration//GEN-END:variables

    

    /*private void generoCartas() {
        int numero;
        boolean elegida = false;
        
 
         while(!elegida){
             numero = (int) (Math.random() * 168) + 1;
         if ( this.cartascogias[numero] == false){
             this.cartascogias[numero] = true;
             this.jTextField1.setText(todosLosPares[numero]);
             elegida = true;
            }
        }
         elegida = false;
         while(!elegida){
             numero = (int) (Math.random() * 168) + 1;
         if ( this.cartascogias[numero] == false){
             this.cartascogias[numero] = true;
             this.jTextField3.setText(todosLosPares[numero]);
             elegida = true;
            }
        }
         elegida = false;
         while(!elegida){
             numero = (int) (Math.random() * 168) + 1;
         if ( this.cartascogias[numero] == false){
             this.cartascogias[numero] = true;
             this.jTextField5.setText(todosLosPares[numero]);
             elegida = true;
            }
        }
                  elegida = false;
         while(!elegida){
             numero = (int) (Math.random() * 168) + 1;
         if ( this.cartascogias[numero] == false){
             this.cartascogias[numero] = true;
             this.jTextField7.setText(todosLosPares[numero]);
             elegida = true;
            }
        }
         elegida = false;
         while(!elegida){
             numero = (int) (Math.random() * 168) + 1;
         if ( this.cartascogias[numero] == false){
             this.cartascogias[numero] = true;
             this.jTextField9.setText(todosLosPares[numero]);
             elegida = true;
            }
        }
         elegida = false;
         while(!elegida){
             numero = (int) (Math.random() * 168) + 1;
         if ( this.cartascogias[numero] == false){
             this.cartascogias[numero] = true;
             this.jTextField11.setText(todosLosPares[numero]);
             elegida = true;
            }
        }
         
    }
    
    private String generoCart(){
        int numero;
        boolean elegida = false;
        String sol ="";
 
         while(!elegida){
             numero = (int) (Math.random() * 168) + 1;
         if ( this.cartascogias[numero] == false){
             this.cartascogias[numero] = true;
             sol = todosLosPares[numero];
             elegida = true;
            }
        }
    return sol;
    }*/
}
